name: Zip Files

on:
  release:
    types: [published]

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1.1
        with:
          files: dist/ manifest.json
          dest: result.zip
      - uses: actions/upload-artifact@v1.1
        with:
          name: my-artifact
          path: ${{ github.workspace }}/result.zip
