name: Zip Files and Upload

on: [push]

jobs:
  build-and-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Zip dist directory
        uses: vimtor/action-zip@v1.1
        with:
          files: dist/
          dest: dist.zip

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-artifact
          path: ${{ github.workspace }}/dist.zip
